### ISSUE TITLE
Dark mode for better ux

### ISSUE THREAD

**Issue by abhayksahu369** [jinx-vi-0/passop#85]
**Is your feature request related to a problem? Please describe.**
many users prefer using websites in dark mode.

**Describe the solution you'd like**
website to have a dark mode, for better ux.

**Comment by adarsh-site** [comment]
Okay, but first, we need to update the UI before adding dark mode.

**Comment by abhayksahu369** [comment]
the ui seems good, what do you want to add @jinx-vi-0 ?

**Comment by adarsh-site** [comment]
I appreciate the suggestion for dark mode, but since this is primarily a password saver web application, user screen time will be minimal. Therefore, adding dark mode might not significantly enhance user experience and could actually complicate the UI unnecessarily. Let's focus on optimizing the current UI instead.
